document.writeln("<style>");
document.writeln("	.mui-plus .plus{");
document.writeln("		display: inline;");
document.writeln("	}");
document.writeln("	.plus{");
document.writeln("		display: none;");
document.writeln("	}");
document.writeln("	#topPopover {");
document.writeln("		position: fixed;");
document.writeln("		top: 16px;");
document.writeln("		right: 6px;");
document.writeln("	}");
document.writeln("	#topPopover .mui-popover-arrow {");
document.writeln("		left: auto;");
document.writeln("		right: 6px;");
document.writeln("	}");
document.writeln("	.mui-popover {");
document.writeln("		height: 200px;");
document.writeln("	}");
document.writeln("	.mui-content {");
document.writeln("		padding: 10px;");
document.writeln("	}");
document.writeln("</style>		");
document.writeln("<header class=\"mui-bar mui-bar-nav\">");
document.writeln("	<a id=\"menu\" class=\"mui-pull-left\" href=\"#topPopover\">");
document.writeln("		<img src=\"../../image/user/user.png\" />");
document.writeln("	</a>");
document.writeln("	<a class=\"mui-action-back mui-btn mui-btn-link mui-pull-right\">关闭</a>");
document.writeln("	<h1 class=\"mui-title\">便利的资源采集体验</h1>");
document.writeln("</header>");
document.writeln("		");
document.writeln("<div id=\"topPopover\" class=\"mui-popover\">");
document.writeln("	<div class=\"mui-popover-arrow\"></div>");
document.writeln("	<div class=\"mui-scroll-wrapper\">");
document.writeln("	<div class=\"mui-scroll\">");
document.writeln("		<ul class=\"mui-table-view\">");
document.writeln("		<li class=\"mui-table-view-cell\"><a  href=\"javascript:void(0)\" onclick=\"sendTask()\">工单列表</a>");
document.writeln("		</li>");
document.writeln("		<li class=\"mui-table-view-cell\"><a href=\"#\">用户权限</a>");
document.writeln("		</li>");
document.writeln("		<li class=\"mui-table-view-cell\"><a href=\"javascript:void(0)\" onclick=\"getPipe()\">管线资源</a>");
document.writeln("		</li>");
document.writeln("		<li class=\"mui-table-view-cell\"><a href=\"#\">内线资源</a>");
document.writeln("		</li>");
document.writeln("		</ul>");
document.writeln("	</div>");
document.writeln("</div>");
document.writeln("</div>");
document.writeln("");
document.writeln("<script>");
document.writeln("	function getPipe(){");
document.writeln("		mui.openWindow(\"/pages/pipe/pipeList.html?resType=\'pipe\'\");");
document.writeln("			setTimeout(function() {");
document.writeln("				plus.webview.currentWebview().close();");
document.writeln("			},");
document.writeln("		1000);");
document.writeln("	}");
document.writeln("	");
document.writeln("</script>");